global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nginx_1_18_0'
    static_configs:
      - targets: ['nginx_exporter_1:9113']
    metrics_path: /metrics

  - job_name: 'nginx_1_25_2'
    static_configs:
      - targets: ['nginx_exporter_2:9113']
    metrics_path: /metrics

  # Optional: Add Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']