services:
  nginx_1.18.0:
    image: nginx:1.18.0
    ports:
      - "8080:80"
    volumes:
      - ./nginx_1.18.0/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_1.18.0/index.html:/usr/share/nginx/html/index.html
  nginx_exporter_1:
    image: nginx/nginx-prometheus-exporter:1.3
    ports:
      - "9113:9113"
    command:
      - -nginx.scrape-uri=http://nginx_1.18.0/stub_status
    depends_on:
      - nginx_1.18.0

  nginx_1.25.2:
    image: nginx:1.25.2
    ports:
      - "8081:80"
    volumes:
      - ./nginx_1.25.2/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_1.25.2/index.html:/usr/share/nginx/html/index.html
  nginx_exporter_2:
    image: nginx/nginx-prometheus-exporter:1.3
    ports:
      - "9114:9113"
    command:
      - -nginx.scrape-uri=http://nginx_1.25.2/stub_status
    depends_on:
      - nginx_1.25.2
      
  grafana:
    image: grafana/grafana:10.1.5
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin

  prometheus:
    image: prom/prometheus:v3.0.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml

